#!/bin/sh

URL=`$WGET -O - 'http://of.openfoundry.org/projects/814/download' | \
        sed -n 's/^.*<a href="\(.*hinedo.*ubuntu.*i386.deb\)">.*$/\1/p' | sed '2,2d'`
if [ x"$DISTRIB_CODENAME" = x"gutsy" -o \
     x"$DISTRIB_CODENAME" = x"hardy" -o \
     x"$DISTRIB_CODENAME" = x"intrepid" ]; then
    scripts/download-install hinedo "$URL"
else
    echo "Hinedo 目前沒有給 $DISTRIB_CODENAME 使用的版本，取消安裝。"
fi
