#!/bin/sh

if [ "$DISTRIB_ID" == "Debian" ]; then
    uri="http://ftp.tw.debian.org/debian-multimedia/"
    comps="main"
elif [ "$DISTRIB_CODENAME" == "Ubuntu" ]; then
    uri="http://packages.medibuntu.org/"
    comps="free non-free"
fi

scripts/add_repos.py "$uri" "$DISTRIB_CODENAME" "$comps" "多媒體套件庫 (Lazyscript 新增)"

apt-get update
apt-get -y --force-yes install w32codecs
